import axios from "axios";

/**
 * AquaMind AI API client.
 *
 * Talks to the FastAPI monolith (SDD Section 10 — /api/v1/*).
 * Dev: vite.config.js proxies /api -> http://127.0.0.1:8000
 * Prod: set VITE_API_BASE_URL to the deployed API origin
 */
const baseURL = (import.meta.env.VITE_API_BASE_URL || "").replace(/\/+$/, "");

export const api = axios.create({
  baseURL,
  timeout: 10000,
});

// Dedicated instance for slow agentic endpoints (multi-agent pipeline via Ollama/Groq)
export const reasonApi = axios.create({
  baseURL,
  timeout: 300000, // 5 minutes timeout for Ollama reasoning
});

// Optional local bearer token support
const token = import.meta.env.VITE_API_TOKEN;
if (token) {
  api.defaults.headers.common["Authorization"] = `Bearer ${token}`;
  reasonApi.defaults.headers.common["Authorization"] = `Bearer ${token}`;
}

// Device ID for multi-device support - matching backend generation
const DEVICE_ID_KEY = "rackpulse_device_id";
const getDeviceId = () => {
  let deviceId = localStorage.getItem(DEVICE_ID_KEY);
  if (!deviceId) {
    // Use the device ID generated by the backend for this machine
    deviceId = "device-5bc6368b8e9ad3d5"; // Matches backend generated ID
    localStorage.setItem(DEVICE_ID_KEY, deviceId);
    console.log('Using backend-generated device ID:', deviceId);
  } else {
    console.log('Using existing device ID:', deviceId);
  }
  return deviceId;
};

// Add device ID to all requests
const deviceId = getDeviceId();
api.defaults.headers.common["X-Device-ID"] = deviceId;
reasonApi.defaults.headers.common["X-Device-ID"] = deviceId;
console.log('Using device ID:', deviceId);

// Override baseURL for development
api.defaults.baseURL = "http://127.0.0.1:8004";
reasonApi.defaults.baseURL = "http://127.0.0.1:8004";

/** GET /api/v1/dashboard/summary -> DashboardSummary */
export const getDashboardSummary = () =>
  api.get("/api/v1/dashboard/summary").then((r) => r.data);

/** GET /api/v1/telemetry/latest -> TelemetryReadingOut */
export const getLatestTelemetry = () =>
  api.get("/api/v1/telemetry/latest").then((r) => r.data);

/** POST /api/v1/telemetry (TelemetryReadingIn) -> { telemetry_id } */
export const postTelemetry = (reading) =>
  api.post("/api/v1/telemetry", reading).then((r) => r.data);

/** POST /api/v1/simulate ({ telemetry_id? }) -> { utilisation, thermal_load_kw, ... } */
export const postSimulate = (telemetry_id) =>
  api.post("/api/v1/simulate", { telemetry_id }).then((r) => r.data);

/** GET /api/v1/watermodel/latest -> WaterModelOut */
export const getLatestWaterModel = () =>
  api.get("/api/v1/watermodel/latest").then((r) => r.data);

/** POST /api/v1/recommend ({ telemetry_id? }) -> RecommendationOut */
export const postRecommend = (telemetry_id) =>
  api.post("/api/v1/recommend", { telemetry_id }).then((r) => r.data);

/** GET /api/v1/recommend/latest -> RecommendationOut */
export const getLatestRecommendation = () =>
  api.get("/api/v1/recommend/latest").then((r) => r.data);

/** GET /api/v1/memory/search?q=&k= -> MemoryOut[] */
export const searchMemory = (q, k = 5) =>
  api.get("/api/v1/memory/search", { params: { q, k } }).then((r) => r.data);

/** GET /api/memory/history?limit= -> Memory history */
export const getMemoryHistory = (limit = 50) =>
  api.get("/api/memory/history", { params: { limit } }).then((r) => r.data);

/** GET /api/memory/comprehensive -> Comprehensive memory and episode stats */
export const getComprehensiveStats = () =>
  api.get("/api/memory/comprehensive").then((r) => r.data);

/** GET /api/v1/reports/daily?format=csv|pdf -> Blob (file stream) */
export const downloadDailyReport = (format = "csv") =>
  api
    .get("/api/v1/reports/daily", { params: { format }, responseType: "blob" })
    .then((r) => r.data);

/** Enterprise APIs */
export const getEnterpriseDashboard = () =>
  api.get("/api/dashboard").then((r) => r.data);

/** POST /api/reason — runs the full multi-agent pipeline via Ollama/Groq with fallback to /api/v1/recommend. */
export const postReason = (telemetry_id, use_memory = true) =>
  reasonApi
    .post("/api/reason", { telemetry_id, use_memory })
    .catch((err) => {
      if (err.response && err.response.status === 404) {
        return reasonApi.post("/api/v1/recommend", { telemetry_id });
      }
      throw err;
    })
    .then((r) => r.data);

/** POST /api/compare — side-by-side memory vs no-memory benchmark (single blocking call) */
export const postCompare = (telemetry_id) =>
  reasonApi.post("/api/compare", { telemetry_id }).then((r) => r.data);

function formatCompareSide(reasonRes, useMemory) {
  return {
    run_id: reasonRes.run_id,
    use_memory: useMemory,
    agent: reasonRes.agent_name || (useMemory ? "langgraph_multi_agent" : "baseline_no_memory"),
    recommendation: reasonRes.recommendation,
    rationale: reasonRes.rationale,
    explanation: reasonRes.explanation,
    confidence: reasonRes.confidence,
    confidence_pct: reasonRes.confidence_pct ?? Math.round((reasonRes.confidence ?? 0) * 100),
    expected_water_saving: reasonRes.expected_water_saving,
    cited_episodes: useMemory ? (reasonRes.cited_episodes_count ?? 0) : 0,
    cited_memory_ids: useMemory ? (reasonRes.historical_evidence?.map((h) => h.memory_id) ?? []) : [],
    matched_memories_count: useMemory ? (reasonRes.matched_memories_count ?? 0) : 0,
    historical_evidence: useMemory ? (reasonRes.historical_evidence ?? []) : [],
  };
}

function buildFailureMemory(failedEpisodes) {
  const failedEp =
    failedEpisodes?.find((e) => e.incident_occurred) ?? failedEpisodes?.[0];
  if (!failedEp?.action_taken) return null;
  const dateStr = failedEp.created_at?.split("T")[0] ?? "a prior run";
  if (failedEp.incident_occurred) {
    return `Avoided strategy '${failedEp.action_taken}' which caused an incident on ${dateStr}.`;
  }
  const rewardStr = failedEp.reward != null ? failedEp.reward.toFixed(2) : "n/a";
  return `Avoided strategy '${failedEp.action_taken}' (reward ${rewardStr}) from ${dateStr}.`;
}

/** Map POST /api/v1/simulate response + optional live dashboard context to scenario card shape. */
export function buildScenarioFromSimulate(simulateRes, liveContext = {}) {
  if (!simulateRes) {
    return {
      telemetry_id: liveContext.telemetry_id,
      rack: liveContext.rack ?? "Primary Rack — Live Telemetry",
      utilisation: liveContext.utilisation ?? liveContext.gpu_pct ?? null,
      thermal_load_kw: liveContext.thermal_load_kw ?? null,
      ambient_temp: liveContext.ambient_temp ?? null,
      humidity: liveContext.humidity ?? null,
      cpu_pct: liveContext.cpu_pct ?? null,
      gpu_pct: liveContext.gpu_pct ?? null,
    };
  }

  const rackLabel =
    simulateRes.rack ??
    (simulateRes.device_id
      ? `${simulateRes.device_id} — Active Cluster`
      : simulateRes.rack_id
        ? `${simulateRes.rack_id} — Active Cluster`
        : liveContext.rack ?? "Primary Rack — Active Cluster");

  return {
    telemetry_id: simulateRes.telemetry_id ?? liveContext.telemetry_id,
    rack_id: simulateRes.rack_id,
    device_id: simulateRes.device_id,
    rack: rackLabel,
    utilisation: simulateRes.utilisation ?? liveContext.utilisation ?? liveContext.gpu_pct,
    thermal_load_kw: simulateRes.thermal_load_kw,
    ambient_temp:
      simulateRes.ambient_temp ??
      simulateRes.water_model?.ambient_temp ??
      liveContext.ambient_temp,
    humidity:
      simulateRes.humidity ??
      simulateRes.water_model?.humidity ??
      liveContext.humidity,
    cpu_pct: simulateRes.cpu_pct ?? liveContext.cpu_pct,
    gpu_pct: simulateRes.gpu_pct ?? liveContext.gpu_pct ?? simulateRes.utilisation,
  };
}

/**
 * Progressive compare benchmark — two sequential LangGraph runs so the UI can
 * show baseline results before the slower memory-enriched run completes.
 *
 * onProgress({ phase, message }) fires at each stage for UX updates.
 */
export async function runCompareBenchmark(telemetry_id, onProgress, liveContext = {}) {
  onProgress?.({ phase: "scenario", message: "Loading live telemetry snapshot from DB…" });
  const simulateRes = await postSimulate(telemetry_id);

  onProgress?.({
    phase: "baseline",
    message: "Running baseline LangGraph pipeline (use_memory=false)…",
  });
  const baselineReason = await postReason(telemetry_id, false);
  const without_memory = {
    ...formatCompareSide(baselineReason, false),
    risk_assessment:
      "Uncertain thermal impact without historical calibration; generic static margins only.",
  };

  // Emit partial result so UI can render baseline panel before memory run finishes
  onProgress?.({
    phase: "baseline_done",
    message: "Baseline complete — starting memory-enriched run…",
    partial: { without_memory, simulateRes },
  });

  onProgress?.({
    phase: "memory",
    message: "Running full agentic pipeline with episode RAG (use_memory=true)…",
  });
  const [memoryReason, successEpisodes, failedEpisodes] = await Promise.all([
    postReason(telemetry_id, true),
    getEpisodesReplay({ success: true, limit: 100 }),
    getEpisodesReplay({ success: false, limit: 10 }),
  ]);

  const with_memory = {
    ...formatCompareSide(memoryReason, true),
    cited_episodes: successEpisodes?.length ?? memoryReason.cited_episodes_count ?? 0,
    failure_memory_avoided: buildFailureMemory(failedEpisodes),
    historical_evidence: (successEpisodes ?? []).slice(0, 5).map((ep) => ({
      episode_id: ep.episode_id,
      action_taken: ep.action_taken,
      reward: ep.reward,
      water_delta_pct: ep.water_delta_pct,
      success: ep.success,
    })),
    explanation:
      memoryReason.explanation ??
      `Grounded in ${successEpisodes?.length ?? 0} resolved success episodes.`,
  };

  const rackLabel =
    liveContext.device_id ?? liveContext.rack_id ?? "Primary Rack";

  return {
    scenario: buildScenarioFromSimulate(simulateRes, {
      ...liveContext,
      rack: liveContext.rack ?? `${rackLabel} — Active Cluster`,
    }),
    without_memory,
    with_memory,
    episodes: {
      success_count: successEpisodes?.length ?? 0,
      failure_count: failedEpisodes?.length ?? 0,
    },
  };
}

export const postMemorySearch = (query, k = 5, memory_type = null) =>
  reasonApi.post("/api/memory/search", { query, k, memory_type }).then((r) => r.data);

export const getIncidents = (severity = null, limit = 20) =>
  api.get("/api/incidents", { params: { severity, limit } }).then((r) => r.data);

export const getRecommendations = (limit = 20) =>
  api.get("/api/recommendations", { params: { limit } }).then((r) => r.data);

// ─── New Memory Architecture APIs (Tasks 4-7) ───────────────────────

/** GET /api/v1/episodes/replay -> Episode[] — resolved episodes for experience replay */
export const getEpisodesReplay = (params = {}) => {
  // Add include_unresolved parameter if needed for dashboard
  const finalParams = { ...params };
  if (params.includeUnresolved !== undefined) {
    finalParams.include_unresolved = params.includeUnresolved;
    delete finalParams.includeUnresolved;
  }
  return api.get("/api/v1/episodes/replay", { params: finalParams }).then((r) => r.data);
};

/** GET /api/v1/fleet/summary -> fleet-wide rack stats */
export const getFleetSummary = () =>
  api.get("/api/v1/fleet/summary").then((r) => r.data);

/** GET /api/v1/agent/trace/recent -> ReasoningEvent[] (REST polling fallback) */
export const getRecentTraces = (run_id = null, limit = 200) =>
  api.get("/api/v1/agent/trace/recent", { params: { run_id, limit } }).then((r) => r.data);

export default api;
